### ISSUE TITLE
EddFcmsPlugin exception

### ISSUE THREAD

**Issue by towdawg** [irtnog/EddFcmsPlugin#1]
### Description

Opened EDDiscovery for the first time after installing plugin [EddFcmsPlugin](https://github.com/irtnog/EddFcmsPlugin)
Asked if I want the DLL included, answered yes, then pow.
### Exception Details:
>EDDiscovery v15.1.4.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at EddFcmsPlugin.EDDClass.EDDConfig(String istr, Boolean editit)
>   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
>   at EliteDangerousCore.DLL.EDDDLLCaller.Config(String istr, Boolean editit) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\DLL\EDDDLLCaller.cs:line 335
>   at EliteDangerousCore.DLL.EDDDLLManager.Load(String[] dlldirectories, Boolean[] disallowautomatically, String ourversion, String[] inoptions, EDDCallBacks callbacks, String& alloweddisallowed, Func`2 getconfig, Action`2 setconfig) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\DLL\EDDDLLManager.cs:line 91
>   at EDDiscovery.EDDiscoveryForm.DLLStart(String& alloweddlls) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryFormHelpers.cs:line 398
>   at EDDiscovery.EDDiscoveryForm.EDDiscoveryForm_Shown(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:line 626
>   at System.Windows.Forms.Form.OnShown(EventArgs e)
>   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
>   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
>   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
>===== END =====
>```

**Comment by towdawg** [comment]
You are amazing, thank you!
________________________________
